# Inventory for AD Sync prosjekt
# Definerer servergrupper og felles tilkoblingsinnstillinger

[linux_srv]
linux01 ansible_host=192.168.56.11
linux02 ansible_host=192.168.56.12

[sync_srv]
linux01 ansible_host=192.168.56.11
linux02 ansible_host=192.168.56.12
filserver ansible_host=192.168.56.50

[web_srv]
webserver ansible_host=192.168.56.40

[fil_srv]
filserver ansible_host=192.168.56.50

[all:children]
linux_srv
web_srv
fil_srv

[linux_srv:vars]
websync_public_key="{{ lookup('file', '../files/keys/websync.pub') }}"

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_become=true
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
